// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20260703191705_InitialCommand2")]
    partial class InitialCommand2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            Description = "10% discount on all laptops",
                            ProductName = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15,
                            Description = "15% discount on selected smartphones",
                            ProductName = "Smartphone"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20,
                            Description = "20% discount on wireless headphones",
                            ProductName = "Headphones"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 5,
                            Description = "5% discount on mechanical keyboards",
                            ProductName = "Keyboard"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 25,
                            Description = "25% discount on 27-inch monitors",
                            ProductName = "Monitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
